name: Full Stack CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code

        uses: actions/checkout@v4

      # ======================
      # Frontend React
      # ======================

      - name: Setup Node

        uses: actions/setup-node@v4

        with:
          node-version: 22

      - name: Install Frontend Dependencies

        run: cd frontend && npm install

      - name: Build React Application

        run: cd frontend && npm run build

      # ======================
      # Backend Laravel
      # ======================

      - name: Setup PHP

        uses: shivammathur/setup-php@v2

        with:
          php-version: "8.4"

          extensions: mbstring, xml, ctype, fileinfo, openssl, pdo, pdo_mysql

      - name: Check PHP Version

        run: php -v

      - name: Install Laravel Dependencies

        run: cd backend && composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Laravel Version Check

        run: cd backend && php artisan --version
