name: Full Stack CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code

        uses: actions/checkout@v4

      # Frontend

      - name: Setup Node

        uses: actions/setup-node@v4

        with:
          node-version: 20

      - name: Install Frontend

        run: cd frontend && npm install

      - name: Build Frontend

        run: cd frontend && npm run build

      # Backend

      - name: Setup PHP

        uses: shivammathur/setup-php@v2

        with:
          php-version: 8.2

      - name: Install Laravel

        run: cd backend && composer install --no-progress

      - name: Laravel Check

        run: cd backend && php artisan --version
